# Generated by Django 5.1.4 on 2025-01-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
